In [3]:
import numpy as np
import pandas as pd

In [4]:
news = pd.read_csv('train.csv')

In [5]:
news.shape

(20800, 5)

In [6]:
news.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [7]:
news.dropna(inplace=True)

In [8]:
news.reset_index(inplace=True)

In [9]:
news

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
18280  Rapper T. I. unloaded on black celebrities who...      0  
18281  When the Green Bay Packers lost to the Washing...      0  
18282  The Macy’s of today grew from the union of sev...      0  
18283  NATO, Russia To Hold Parallel Exercises In Bal...      1  
18284    David Swanson is an author, activist, journa...      1  

[18285 rows x 6 columns]

In [10]:
news.drop(columns=['index','id'], inplace=True)

In [11]:
news

title  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...   
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2                      Why the Truth Might Get You Fired   
3      15 Civilians Killed In Single US Airstrike Hav...   
4      Iranian woman jailed for fictional unpublished...   
...                                                  ...   
18280  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  Macy’s Is Said to Receive Takeover Approach by...   
18283  NATO, Russia To Hold Parallel Exercises In Bal...   
18284                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
18280  Rapper T. I. unloaded on black celebrities who...      0  
18281  When the Green Bay Packers lost to the Washing...      0  
18282  The Macy’s of today grew from the union of sev...      0  
18283  NATO, Russia To Hold Parallel Exercises In Bal...      1  
18284    David Swanson is an author, activist, journa...      1  

[18285 rows x 4 columns]

In [12]:
# Spliting input and target dataset
x = news.drop(columns='label')
y = news.label

In [13]:
x

title  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...   
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2                      Why the Truth Might Get You Fired   
3      15 Civilians Killed In Single US Airstrike Hav...   
4      Iranian woman jailed for fictional unpublished...   
...                                                  ...   
18280  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  Macy’s Is Said to Receive Takeover Approach by...   
18283  NATO, Russia To Hold Parallel Exercises In Bal...   
18284                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 3 columns]

In [14]:
y

0        1
1        0
2        1
3        1
4        1
        ..
18280    0
18281    0
18282    0
18283    1
18284    1
Name: label, Length: 18285, dtype: int64

# Preprocessing

In [15]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re     # regular expression

In [15]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/nilavo/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
ps = PorterStemmer()

In [17]:
nilavo = []
for i in x['title']:
    i = re.sub('[^a-zA-Z]',' ',i)
    i = i.lower().split()
    i = [ps.stem(j) for j in i if not j in stopwords.words('english')]
    i = ' '.join(i)
    nilavo.append(i)

In [18]:
nilavo

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [19]:
import tensorflow

In [20]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [21]:
vocabulary_size = 10000
onehot = [one_hot(i, vocabulary_size) for i in nilavo]
onehot

[[9478, 3592, 7607, 9788, 4067, 756, 9575, 5597, 1844, 8048],
 [2346, 7359, 9533, 1716, 4315, 5241, 2771],
 [5348, 2301, 9919, 7258],
 [4160, 5760, 9956, 4021, 1349, 7421],
 [6248, 4315, 3650, 1907, 5243, 5938, 4315, 1051, 2833, 6328],
 [9016,
  4308,
  4081,
  2015,
  7143,
  9099,
  8414,
  2105,
  509,
  5932,
  2555,
  2565,
  9949,
  4202,
  2771],
 [1577, 5163, 8486, 8302, 6308, 8086, 1176, 6996, 5866, 2231, 4031],
 [7986, 2085, 1165, 8853, 2660, 8981, 9099, 3165, 5866, 2231, 4031],
 [3881, 9279, 5878, 9607, 6550, 6269, 8120, 4720, 9099, 2422],
 [5397, 2301, 2536, 8273, 1077, 2344, 3395, 5620],
 [6172, 7113, 646, 7856, 7419, 1440, 6318, 4897, 8347, 3836, 7193],
 [4021, 599, 4067, 6269, 9099, 2660],
 [336, 1280, 4854, 7155, 7162, 172, 1157, 2595, 368],
 [1794, 5984, 257, 9866, 6096, 5763, 3375, 5866, 2231, 4031],
 [9493, 6766, 2206, 6685, 2900, 5866, 2231, 4031],
 [7292, 987, 1920, 8284, 8757, 8151, 5400, 5816, 4294, 9406],
 [8985, 6826, 7359],
 [2992, 6363, 1527, 8628, 9099, 7819

In [22]:
onehot_pad = pad_sequences(onehot, padding='pre', maxlen=20)
onehot_pad

array([[   0,    0,    0, ..., 5597, 1844, 8048],
       [   0,    0,    0, ..., 4315, 5241, 2771],
       [   0,    0,    0, ..., 2301, 9919, 7258],
       ...,
       [   0,    0,    0, ..., 5866, 2231, 4031],
       [   0,    0,    0, ..., 7143, 7716, 7268],
       [   0,    0,    0, ..., 3257, 7983, 3217]], dtype=int32)

In [23]:
onehot_pad[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 9478,
       3592, 7607, 9788, 4067,  756, 9575, 5597, 1844, 8048], dtype=int32)

In [24]:
len(onehot_pad[0])

20

# Creating Model

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.optimizers import Adam

In [26]:
features = 40
def build(hp):
    model = Sequential()
    model.add(Embedding(vocabulary_size, features, input_length= 20))
    model.add(LSTM(hp.Int('neurons', min_value=32, max_value=512, step=16)))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer=Adam(hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])), metrics=['accuracy'])
    return model

In [27]:
from kerastuner import RandomSearch

/var/folders/d8/9p7yb1wn27l_2y2lp6pcbdz00000gn/T/ipykernel_47468/659161079.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  from kerastuner import RandomSearch


In [29]:
tuner_search = RandomSearch(
    build,
    objective='val_accuracy',
    max_trials=5,
    directory='output',
    project_name="Fake news"
)

2021-12-28 21:34:20.887898: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-12-28 21:34:20.888674: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



# Model training

In [30]:
onehot_pad.shape, y.shape

((18285, 20), (18285,))

In [32]:
from sklearn.model_selection import train_test_split as tts
x_train, x_test, y_train, y_test = tts(np.array(onehot_pad), np.array(y), test_size= 0.3, random_state= 42)

In [34]:
tuner_search.search(x_train, y_train, epochs=3, validation_split= 0.1)

Trial 5 Complete [00h 00m 39s]
val_accuracy: 0.7734375

Best val_accuracy So Far: 0.9125000238418579
Total elapsed time: 00h 02m 35s
INFO:tensorflow:Oracle triggered exit


In [37]:
model=tuner_search.get_best_models(num_models=1)[0]

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            400000    
                                                                 
 lstm (LSTM)                 (None, 320)               462080    
                                                                 
 dense (Dense)               (None, 1)                 321       
                                                                 
Total params: 862,401
Trainable params: 862,401
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=10, batch_size=64)

2021-12-24 10:51:05.050553: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


Epoch 1/10


2021-12-24 10:51:05.718470: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2021-12-24 10:51:05.976333: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2021-12-24 10:51:06.151556: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


200/200 [==============================] - ETA: 0s - loss: 0.4467 - accuracy: 0.7725

2021-12-24 10:51:11.518990: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2021-12-24 10:51:11.608475: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


200/200 [==============================] - 7s 31ms/step - loss: 0.4467 - accuracy: 0.7725 - val_loss: 0.2891 - val_accuracy: 0.8753
Epoch 2/10
200/200 [==============================] - 5s 27ms/step - loss: 0.2666 - accuracy: 0.8959 - val_loss: 0.2705 - val_accuracy: 0.8895
Epoch 3/10
200/200 [==============================] - 5s 26ms/step - loss: 0.2603 - accuracy: 0.8962 - val_loss: 0.2694 - val_accuracy: 0.8925
Epoch 4/10
200/200 [==============================] - 5s 27ms/step - loss: 0.2564 - accuracy: 0.8968 - val_loss: 0.2625 - val_accuracy: 0.8906
Epoch 5/10
200/200 [==============================] - 5s 26ms/step - loss: 0.2513 - accuracy: 0.8975 - val_loss: 0.2722 - val_accuracy: 0.8939
Epoch 6/10
200/200 [==============================] - 5s 26ms/step - loss: 0.2457 - accuracy: 0.8969 - val_loss: 0.2547 - val_accuracy: 0.8884
Epoch 7/10
200/200 [==============================] - 5s 26ms/step - loss: 0.2393 - accuracy: 0.8997 - val_loss: 0.2500 - val_accuracy: 0.8914
Epoch 8/10

In [40]:
y_pred = model.predict(x_test)

2021-12-28 22:55:02.339603: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2021-12-28 22:55:02.462450: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


In [41]:
y_pred

array([[9.7771466e-01],
       [1.6927616e-03],
       [7.4798177e-04],
       ...,
       [9.8516405e-01],
       [2.8819391e-03],
       [8.2482284e-01]], dtype=float32)

In [42]:
t = []
for i in y_pred:
    if i < 0.5:
        i=0
    else:
        i=1
    t.append(i)

In [43]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, t)

array([[2618,  489],
       [  72, 2307]])

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, t)

0.8977397010572365